"""Init

Revision ID: a5182c75ae87
Revises: 
Create Date: 2023-04-13 23:23:07.154667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5182c75ae87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    postgresql_partition_by='HASH (id)'
    )
    op.create_table('login_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=80), nullable=True),
    sa.Column('auth_datetime', sa.DateTime(), nullable=False),
    sa.Column('user_device_type', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'user_device_type'),
    postgresql_partition_by='LIST (user_device_type)'
    )

    op.execute("""
    CREATE TABLE login_history_web PARTITION OF login_history FOR VALUES IN ('web');
    CREATE TABLE login_history_mobile PARTITION OF login_history FOR VALUES IN ('mobile');
    CREATE TABLE login_history_other PARTITION OF login_history FOR VALUES IN ('other');
    """)

    op.execute("""
    CREATE TABLE users_0 PARTITION OF users FOR VALUES WITH (MODULUS 4, REMAINDER 0);
    CREATE TABLE users_1 PARTITION OF users FOR VALUES WITH (MODULUS 4, REMAINDER 1);
    CREATE TABLE users_2 PARTITION OF users FOR VALUES WITH (MODULUS 4, REMAINDER 2);
    CREATE TABLE users_3 PARTITION OF users FOR VALUES WITH (MODULUS 4, REMAINDER 3);

    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    DROP TABLE IF EXISTS login_history_web;
    DROP TABLE IF EXISTS login_history_mobile;
    DROP TABLE IF EXISTS login_history_other;
    """)
    
    op.execute("""
    DROP TABLE IF EXISTS users_1;
    DROP TABLE IF EXISTS users_2;
    DROP TABLE IF EXISTS users_3;
    DROP TABLE IF EXISTS users_4;
    """) 
    op.drop_table('login_history')
    op.drop_table('users')
    op.drop_table('role')
    # ### end Alembic commands ###
